Gh 10083
Automattic/mongoose pull request #10167
Opened 2021-04-21 20:17 UTC by IslandRhythms

failure is from a test that needs to be adjusted

2021-04-21 21:54 UTC, vkarpov15 requested changes

2021-04-21 21:54 UTC, vkarpov15 commented on lib/model.js
> +    saveOptions = { writeConcern: saveOptions };
This really should be `saveOptions.writeConcern = options.writeConcern` or something like that. Why overwrite all `saveOptions`?

2021-04-21 21:54 UTC, vkarpov15 commented on lib/model.js
> +      saveOptions.checkKeys = options.writeConcern.checkKeys;
`checkKeys` isn't a write concern option. I think this is only an issue because you're mistakenly overwriting all of `saveOptions` below.

2021-04-22 23:07 UTC, vkarpov15 requested changes
I took a look and the query test still fails. We're going to have to make some changes to how `Query.prototype.j`, `Query.prototype.w`, and `Query.prototype.wtimeout` functions work, see https://github.com/Automattic/mongoose/blob/9f9173c81b1daa6a6cb70421575404fb6cd6fae8/lib/query.js#L1209 . That will need an `if` statement like:

```javascript
if (this.options.writeConcern != null) {
  this.options.writeConcern.j = val;
} else {
  this.options.j = val;
}
```

2021-04-23 17:57 UTC, vkarpov15 requested changes

2021-04-23 17:57 UTC, vkarpov15 commented on lib/model.js
> +    saveOptions = { writeConcern: saveOptions };
You really shouldn't be overwriting `saveOptions` here. You'd be removing all other top-level `saveOptions`, like `session`. Instead, do something like:

```javascript
saveOptions.writeConcern = Object.assign({}, options.writeConcern);
```

2021-04-23 17:57 UTC, vkarpov15 commented on lib/query.js
> +  else {
Formatting: `else` on the same line as `{`

2021-04-23 17:57 UTC, vkarpov15 commented on lib/query.js
> +      options.writeConcern.j = options.j;
Nice :+1: Good job finding the right place to fix this.

2021-04-23 18:35 UTC, IslandRhythms commented
So something I noticed after the commit is that the first operation ran from 10083 looks like this with `Object.assign` 
```
Mongoose: Test.insertOne({ _id: 12345678, op: 'help', size: 54, totalSize: 104 }, { w: 'majority', j: true, wtimeout: 15000, writeConcern: { w:
 'majority', j: true, wtimeout: 15000 }, session: null})

```
its fine after that

2021-04-23 19:02 UTC, IslandRhythms commented
I got it

2021-04-26 21:21 UTC, vkarpov15 approved these changes
Thanks :+1:

2021-04-26 21:22 UTC, merged