Feat 10316: Can now do a dryRun of syncIndexes using Model.diffIndexes()
Automattic/mongoose pull request #10362
Opened 2021-06-15 20:54 UTC by IslandRhythms

2021-06-16 20:45 UTC, vkarpov15 requested changes

2021-06-16 20:45 UTC, vkarpov15 commented on test/model.indexes.test.js
> +        const User = db.model('Upson', userSchema);
Add a `yield User.init()` here to wait for all indexes to finish building

2021-06-16 20:45 UTC, vkarpov15 commented on lib/model.js
> +          } else {
You may end up adding the same index to `toCreate` multiple times. If you have 3 indexes in MongoDB, you'll execute the `schemaIndexes()` loop 3 times and end up adding the same schema index twice each time.

You would likely need to write a separate `for` loop to correctly compute `toCreate`

2021-06-16 21:37 UTC, IslandRhythms commented
Do you want me to go back in and add the comments to describe what diffIndexes() does or do you got it?

2021-06-17 17:45 UTC, vkarpov15 commented
@IslandRhythms please add comments, that would be very helpful :+1:

2021-06-21 14:39 UTC, vkarpov15 approved these changes
Good work, this looks great :+1:

2021-06-21 14:39 UTC, merged