Fix Schema's clone function typing
Automattic/mongoose pull request #10951
Opened 2021-11-03 14:23 UTC by StefanoA1

**Summary**
The Schema's clone function does not preserve the typing (and on its best case, it loses the name of the type and just types the cloned schema as a nameless object)

**Examples**
Before:
clone returns an untyped schema (or at best it returns an object but the type name/interface/class is lost)

After:
clone returns a typed schema which can be the original type or a type that extends the base type (would work for type extending it with partial params)

2021-11-03 20:34 UTC, vkarpov15 requested changes
I'm supportive of adding a generic param to `clone()`, but I'm not sure making `clone()` return something other than `this` is the right call. For one thing, you're missing a bunch of generic parameters to `Schema`. And I can confirm that [`this` respects generics](https://www.typescriptlang.org/play?#code/MYGwhgzhAECyCeBhcUA8AVAfNA3gWAChpoA3MEALmnQG5DDjgB7AOwgBcAnAV2Hac4AKMpWoBKXA2LR2ACwCWEAHQjoAXlLk6RaAF96O0KwCmgsVTmLJO4p2PtunFjIURtxXdqkBze+jNU6NbS0HYOTi6KKlpS+gRxhMxs7NBMAEYAVurQLMYA7nBIKBCoHJzyLN6YggDk7MYcNWJeBEkcqZkATNnpGUpGuWYtbSllPV1Kvuz+zYRlSvwAqgAOy8aciJCmzUA)

Can't we do `clone<T = this>(): T`?

2021-11-04 16:57 UTC, StefanoA1 commented
> I'm supportive of adding a generic param to `clone()`, but I'm not sure making `clone()` return something other than `this` is the right call. For one thing, you're missing a bunch of generic parameters to `Schema`. And I can confirm that [`this` respects generics](https://www.typescriptlang.org/play?#code/MYGwhgzhAECyCeBhcUA8AVAfNA3gWAChpoA3MEALmnQG5DDjgB7AOwgBcAnAV2Hac4AKMpWoBKXA2LR2ACwCWEAHQjoAXlLk6RaAF96O0KwCmgsVTmLJO4p2PtunFjIURtxXdqkBze+jNU6NbS0HYOTi6KKlpS+gRxhMxs7NBMAEYAVurQLMYA7nBIKBCoHJzyLN6YggDk7MYcNWJeBEkcqZkATNnpGUpGuWYtbSllPV1Kvuz+zYRlSvwAqgAOy8aciJCmzUA)
> 
> Can't we do `clone<T = this>(): T`?

I agree, but then T should ensure to extend Schema<DocType> at least (to ensure that not any type is taken as a generic here), what are your thoughts on:
`clone<T extends Schema<DocType> = this>(): T;`
then ?

2021-11-06 18:41 UTC, vkarpov15 commented
Unfortunately not. 2 reasons: 1) `T extends Schema<DocType>` is missing a bunch of generic parameters, and 2) `extends` sometimes has some serious performance issues, see #10349 .

2021-11-06 18:41 UTC, vkarpov15 approved these changes

2021-11-06 18:41 UTC, merged

2021-11-08 09:58 UTC, StefanoA1 commented
@vkarpov15 ah! interesting, do you happen to have any docs on why extends causes such perf issues? thanks for the link

2021-11-11 19:28 UTC, vkarpov15 commented
Wish I knew, but I'm not experienced enough with TS internals to know why sometimes `extends` in generics is such a perf issue.