Strict populate global
Automattic/mongoose pull request #11006
Opened 2021-11-23 18:09 UTC by IslandRhythms

2021-11-23 20:22 UTC, vkarpov15 requested changes

2021-11-23 20:22 UTC, vkarpov15 commented on lib/helpers/populate/getModelsMapForPopulate.js
> +  if (model.schema.base.options.strictPopulate == false && options.strictPopulate == null) {
`model.schema.base.options.strictPopulate != null`. Why hardcoding false?

Also, `model.base.options` should work and be shorter.

Finally, any way to move this up to the `populate()` function in `model.js` that calls `getModelsMapForPopulate()` and shallow clone the object before modifying? A bit random to modify this option here.

2021-11-25 04:47 UTC, AbdelrahmanHafez commented on test/index.test.js
> +  it('allows global `strictPopulate` option (gh-10694)', async function() {
Splitting each test case into a different `it(...)` invocation makes it easier to understand the intention.

I'd split the test here into the following different test cases:
```js
it('global `strictPopulate` works when false')
it('`global `strictPopulate` works when true');
it('global `strictPopulate` can be overriden on a specific query set to false')
it('global `strictPopulate` can be overriden on a specific query set to true')
```

And I'd do my best to make the test case look like a real-world scenario by avoiding variable names such as `test` on line 708.

2021-11-25 04:49 UTC, AbdelrahmanHafez commented
Nice!
Other than this minor test modification, looks great to me. 👍

2021-11-25 04:50 UTC, AbdelrahmanHafez requested changes
Nice!
Other than [the minor test modifications](https://github.com/Automattic/mongoose/pull/11006/files#r756568918), looks great to me. 👍

2021-11-27 20:02 UTC, vkarpov15 reviewed
I agree with @AbdelrahmanHafez 's comments, but otherwise LGTM :+1:

2021-11-29 18:18 UTC, AbdelrahmanHafez approved these changes
Looks good to me. Thanks!

2021-12-02 17:16 UTC, vkarpov15 approved these changes
Nice, good job :+1:

2021-12-02 17:17 UTC, merged