Sync indexes global option
Automattic/mongoose pull request #11222
Opened 2022-01-13 17:47 UTC by IslandRhythms

Why can't I do `await Model.listIndexes().length` off the rip but instead have to save it to a variable? Just curious.

2022-01-15 17:46 UTC, vkarpov15 commented
"Why can't I do await Model.listIndexes().length off the rip but instead have to save it to a variable? Just curious."

Order of operations. `Model.listIndexes()` returns a promise, not an array. So `await Model.listIndexes().length` means "get the `.length` property of `Model.listIndexes()`, and `await` on the result", which isn't what you want.

You can do `(await Model.listIndexes()).length`, or `await Model.listIndexes().then(res => res.length)`

2022-01-15 18:17 UTC, vkarpov15 requested changes

2022-01-15 18:17 UTC, vkarpov15 commented on test/index.test.js
> +      const syncSchema = new m.Schema({ title: String });
In order to test that `syncIndexes()` correctly adds new indexes as well as drops old indexes, let's add a property that isn't `name` or `title`, and add an index to that new property in the schema.

2022-01-15 18:17 UTC, vkarpov15 commented on test/index.test.js
> +      assert.equal(Index.length, 1);
Assert that this index is an index on `_id`.

2022-01-18 16:41 UTC, IslandRhythms commented
Mongoerror, ns not found. The test passes on my machine so I don't know why it's failing here.

2022-01-18 19:28 UTC, Uzlopak commented on test/index.test.js
> +      await m.deleteModel('Sync');
I think this line seems to also force mongoose to drop the collection, which probably does not exist. thats why you get the ns not found error

2022-01-20 02:12 UTC, vkarpov15 requested changes

2022-01-20 02:12 UTC, vkarpov15 commented on test/index.test.js
> +      await syncFalse.collection.dropIndexes();
I think you need to get rid of this line to fix the tests. The problem is that the 'Sync' collection doesn't exist yet when you're calling `dropIndexes()` here.

2022-01-20 19:09 UTC, vkarpov15 approved these changes
Thanks :+1: will merge into 6.2

2022-01-20 19:09 UTC, merged