initial version of msgFunction
Automattic/mongoose pull request #11409
Opened 2022-02-16 12:38 UTC by Uzlopak

@AbdelrahmanHafez 
@vkarpov15 

I wonder if you can figure out what I did here ;).

2022-02-17 18:18 UTC, Uzlopak commented
Dont merge this yet ;)

2022-02-17 18:27 UTC, vkarpov15 commented
Faster handling of `{VALUE}` and other properties in error messages I presume?

2022-02-17 18:40 UTC, Uzlopak commented
Exactly :). But using this everywhere relevant seems to be kind of hard...

2022-02-24 13:04 UTC, AbdelrahmanHafez commented
Thanks @Uzlopak 

I can see that this is related to parsing validation error messages, but I'm finding it a bit difficult to understand how this is meant to be used.

Other than verifying that the code works, unit tests also show examples of how the author meant for the code to be used.
Would happily help replace the code all over the place to use this once I understand how to use it.

2022-02-24 13:07 UTC, AbdelrahmanHafez requested changes

2022-02-24 13:07 UTC, AbdelrahmanHafez commented on lib/error/msgFunction.js
> +module.exports = function msgFunction(msg) {
I've always found that it helps in code readability to name functions as verbs:
```js
const replaceMessage = getMessageReplacer(msg); // vs msgFunction(msg)
const parsedMesage = replaceMessage(someVariable);
```

2022-04-22 18:18 UTC, closed without merging