fix(typescript): `aggregate.sort()` also accepts a string
Automattic/mongoose pull request #11479
Opened 2022-03-04 18:21 UTC by simonbrunel

When using TypeScript, calling `model.aggregate().sort("-name")` generates the following error:

```
Argument of type 'string' is not assignable to parameter of type 'Record<string, 1 | -1 | { $meta: "textScore"; }>'
```

According to the [current implementation](https://github.com/Automattic/mongoose/blob/18cb0bed7256784701d7b75e160707895a0e50db/lib/aggregate.js#L573) (and per the mongoose docs), `aggregate().sort()` also accepts a string.

2022-03-04 23:09 UTC, AbdelrahmanHafez requested changes
Please add a test case verifying the type under test/typescript to avoid this being changed some time in the future.

2022-03-04 23:10 UTC, AbdelrahmanHafez commented
Other than the test case, LGTM.
Thanks 👍

2022-03-05 08:48 UTC, simonbrunel commented
> Please add a test case verifying the type under test/typescript to avoid this being changed some time in the future.

**+1000**, I though there was no test for types (I expected to find them under `types/test` and missed the ones in `test/types`).

Since there was no test for `aggregate.sort()`, I added them for all args supported by the current implementation. Note that `asc`, `ascending`, `desc`, `descending` was also not supported by the current type definition.

2022-03-05 16:21 UTC, Uzlopak commented
Yeah, it is nice to see that the typings tests

2022-03-05 19:00 UTC, AbdelrahmanHafez approved these changes
LGTM, Thanks 👍

2022-03-05 19:00 UTC, merged