types: improve lastErrorObject typing for rawResults
Automattic/mongoose pull request #11602
Opened 2022-03-30 20:45 UTC by simllll

**Summary**

This improves the type for lastErrorObject, this helps to use the correct values as there is for example no modifiedCount or other things that a simple updateOne returns.

**Examples**

```ts
const result = Model.findOneAndUpdate(query, {
								$inc: { occurence: 1 },
							},
							{
								upsert: true,
								returnDocument: 'after',
								rawResult: true
							}
						);

// should work
updateResult.lastErrorObject?.upserted
// should throw error
updateResult.lastErrorObject?.modifiedCount
```

2022-03-30 21:22 UTC, Uzlopak commented
Hi Simon,

Lgtm. Could you please add your Sample Code to the typings Tests in test/types? I guess models.test.ts is the fitting file.

Maybe also add an error test?

Like 
`expectError(updateResult.lastErrorObject?.invalid);`
?

Greetings from Teheran to Vienna :)

2022-03-31 08:08 UTC, AbdelrahmanHafez requested changes
Thanks 👍
I second Uzlopak's comment, would be nice if we can have tests.

2022-03-31 13:09 UTC, simllll commented
I've added a test in queries.test.ts as there are also some other similar tests in it already. Let me know if I should move it to models or another file if you think it fits better somewhere else.

2022-03-31 13:18 UTC, Uzlopak approved these changes
Lgtm

2022-03-31 15:42 UTC, AbdelrahmanHafez approved these changes
LGTM, thanks 👍

2022-03-31 15:43 UTC, merged