Refactor doc.populate FN type.
Automattic/mongoose pull request #11649
Opened 2022-04-08 21:30 UTC by mohammad0-0ahmad

Related to : https://github.com/Automattic/mongoose/issues/11598

2022-04-09 02:00 UTC, mohammad0-0ahmad commented on types/document.d.ts
> +    populate<Paths = {}>(path: string | PopulateOptions | (string | PopulateOptions)[], select?: string | AnyObject, model?: Model<unknown>, match?: AnyObject, options?: PopulateOptions, callback?: C
Should option argument be existing?

2022-04-10 19:16 UTC, Uzlopak commented on types/document.d.ts
> +    populate<Paths = {}>(path: string | PopulateOptions | (string | PopulateOptions)[], select?: string | AnyObject, model?: Model<unknown>, match?: AnyObject, options?: PopulateOptions, callback?: C
@vkarpov15

2022-04-20 21:52 UTC, vkarpov15 requested changes

2022-04-20 21:52 UTC, vkarpov15 commented on test/types/document.test.ts
> +  const doc = await Test.findOne();
You can do `await Test.findOne().orFail()` and avoid the need for `?.` below

2022-04-20 21:52 UTC, vkarpov15 commented on types/document.d.ts
> +    populate<Paths = {}>(path: string | PopulateOptions | (string | PopulateOptions)[], select?: string | AnyObject, model?: Model<unknown>, match?: AnyObject, options?: PopulateOptions, callback?: C
Yes it should.

2022-04-20 21:52 UTC, vkarpov15 commented on types/document.d.ts
> -    populate<Paths = {}>(path: string, names: string, callback: Callback<this & Paths>): void;
Don't get rid of these. The issue is that, if there's more than 1 non-callback arg, `path` must be a string. We don't support `populate(PopulateOptions, string, Model<unknown>)`, for example. So keep this syntax.

2022-04-21 03:49 UTC, mohammad0-0ahmad commented
@vkarpov15 
I've noticed that when rebasing this PR on top of master branch, the model loose and doc for example lose its type & become any.
Although, all tests are passed.
Can u please double-check this?
![Untitled](https://user-images.githubusercontent.com/50488054/164368356-fe492609-4bfb-41d8-b4bb-7eab7e1d0e37.png)

2022-04-22 17:41 UTC, vkarpov15 approved these changes
Nice work, thanks :+1:

2022-04-22 17:41 UTC, merged