added global `id` option to disable id on schemas
Automattic/mongoose pull request #12067
Opened 2022-07-07 19:09 UTC by IslandRhythms

2022-07-08 11:50 UTC, AbdelrahmanHafez requested changes
This is great, thanks!

Can you add TS types+test to the PR as well?

Also, is there an option to set this on schema definition or only as a global option for now? It'd be nice if we can have an option to do that on the schema, but we can do it on a future PR.

2022-07-15 01:32 UTC, vkarpov15 requested changes
Also add `id` to the TypeScript definitions for global Mongoose options here: https://github.com/Automattic/mongoose/blob/d742f4e71a026bc26acae0b4a797108af134f319/types/mongooseoptions.d.ts

2022-07-15 03:35 UTC, AbdelrahmanHafez commented
Thanks, I didn't know that.
@vkarpov15

2022-07-17 22:49 UTC, AbdelrahmanHafez approved these changes

2022-07-19 15:56 UTC, vkarpov15 approved these changes

2022-07-20 15:06 UTC, merged