added schema level lean option
Automattic/mongoose pull request #12081
Opened 2022-07-08 15:43 UTC by IslandRhythms

2022-07-08 15:55 UTC, IslandRhythms commented
It's complaining about one line in model.js that
- I did not touch
- is the comments for the `buildBultWriteOperations` where the line is the indented `@param`

2022-07-08 16:24 UTC, AbdelrahmanHafez requested changes
Nice, thanks! 👍
Can you also add the option to the JSDoc and TS type definitions + TS tests?

Also, what do you think of calling it `defaultLean` instead of `lean`?

How would we go about overriding that for a specific query? I think we can `.setOptions({ lean: false });`, I also think it might be useful to have a `.notLean()` method that does the reverse of `.lean()`.

2022-07-08 16:25 UTC, AbdelrahmanHafez commented on lib/query.js
> +  if (this.schema && 'lean' in this.schema.options) {
Do we also need to check if the user is passing a lean value?
```suggestion
  if (options.lean == null && this.schema && 'lean' in this.schema.options) {
```

2022-07-15 01:36 UTC, vkarpov15 commented on test/schema.test.js
> +    assert.equal(entry instanceof mongoose.Document, false);
Add an extra check in this test that verifies you can still overwrite `lean()`.

So `const doc = await Test.findOne().lean(false); assert.ok(entry instanceof mongoose.Document)`

Also, no need to do  `assert.equal(entry instanceof mongoose.Document, false);`. Just `assert.ok(!entry instanceof mongoose.Document);`

2022-07-22 00:10 UTC, merged