fix(types): better typescript support for schema plugins
Automattic/mongoose pull request #12139
Opened 2022-07-22 13:19 UTC by emiljanitzek

**Summary**

Found more problems when working with typescript and plugins. Since the Schema type sets default values (empty object) for `TInstanceMethods`, `TQueryHelpers` and `TStaticMethods` we need to be able to pass along these types when trying to create query helpers/virtuals/methods/statics.

This PR also contains the fix for Schema and model mismatch. Will rebase this if the other PR gets accepted.

**Examples**

Added `plugin.tests.ts` for examples

2022-07-25 19:00 UTC, vkarpov15 requested changes

2022-07-25 19:00 UTC, vkarpov15 commented on types/index.d.ts
> +      name: keyof TVirtuals,
Same with above. This change is a bit risky.

2022-07-26 08:49 UTC, emiljanitzek commented
Thanks for the feedback @vkarpov15. I've updated the types and added test for this as well.

2022-07-26 22:38 UTC, vkarpov15 approved these changes

2022-08-03 21:00 UTC, vkarpov15 commented
Looks like there were some merge conflict issues, because tests are failing now. Can you please patch that up @emiljanitzek ?

I took a look and it looks like this change doesn't cause any significant performance degradation.

2022-08-08 14:48 UTC, emiljanitzek commented
@vkarpov15 rebased and fixed the conflicts.

2022-08-09 15:58 UTC, merged