Move Scripts to a sub-directory and enhance usage
Automattic/mongoose pull request #12218
Opened 2022-08-05 13:08 UTC by hasezoey

**Summary**

This PR does:
- move all scripts (like `website.js` and `static.js`) to a sub-directory (named `scripts`)
- update `website.js` and `static.js` to be used easier
  - update `website.js` to export its functions
  - update `static.js` to call `website.js`'s functions and also start the watch mode
  - update `package.json` to only call `static.js` for `docs:view`
- renames a variable from `jade` to `pug` to be not confusing

2022-08-05 13:22 UTC, Uzlopak commented on package.json
> +    "docs:view": "node ./scripts/static.js",
If you do this you probably have to modify a markdown file i think.

2022-08-05 13:24 UTC, Uzlopak requested changes
add `npm run docs:generate ` to this documentation

https://github.com/Automattic/mongoose/blob/master/CONTRIBUTING.md#documentation

2022-08-05 13:24 UTC, Uzlopak commented on package.json
> +    "docs:view": "node ./scripts/static.js",
see below

2022-08-05 13:27 UTC, hasezoey commented
> add npm run docs:generate to this documentation

and what should it do? just call `website.js`?

2022-08-05 13:31 UTC, hasezoey commented
> add npm run docs:generate to this documentation

what exactly should be added there and where? because currently the documentation (where `docs:view` is listed) says:

> If you'd like to preview your documentation changes, first commit your changes to your local master branch, then execute:

emphasis on `preview` (ie starting the webserver)

2022-08-05 13:32 UTC, Uzlopak commented
Well if you dont generate than you dont see the result I think

2022-08-05 13:33 UTC, hasezoey commented
> Well if you dont generate than you dont see the result I think

then please read what this PR does again:
> update website.js and static.js to be used easier 
> update static.js to call website.js's functions and also start the watch mode

2022-08-05 13:37 UTC, Uzlopak commented
ah nice

2022-08-06 12:08 UTC, Uzlopak commented
Yesterday when i tested it it seems that index.html was not send with the correct content encoding. I will test it tonight again

2022-08-06 12:09 UTC, hasezoey commented
> Yesterday when i tested it it seems that index.html was not send with the correct content encoding. I will test it tonight again

weird, though i did not change anything regarding encoding that i know of, also which `index.html` are you meaning?

2022-08-06 14:00 UTC, hasezoey commented
I just noticed that there is another script, but i am not sure about so i will do it in a later PR, named `docs/search.js` which is seemingly only meant to generate the search when deployed

2022-08-08 16:09 UTC, vkarpov15 commented on docs/splitApiDocs.js
> -const jade = require('pug');
:man_facepalming: thanks

2022-08-08 16:09 UTC, vkarpov15 approved these changes
Thanks :+1:

2022-08-08 16:10 UTC, merged