Fixed replaceOne model's return type
Automattic/mongoose pull request #12351
Opened 2022-08-29 13:42 UTC by lpizzinidev

Addresses #12347

2022-08-29 14:04 UTC, AbdelrahmanHafez requested changes
LGTM, thanks 👍

Can you also add TS tests to prevent future regressions?

2022-08-29 15:24 UTC, lpizzinidev commented
@AbdelrahmanHafez Sure 👍

2022-08-30 13:35 UTC, Uzlopak commented on test/types/models.test.ts
> +};
```suggestion
}

```

2022-08-30 13:35 UTC, AbdelrahmanHafez approved these changes
LGTM, thanks 👍

2022-08-30 13:38 UTC, AbdelrahmanHafez commented on test/types/models.test.ts
> +  expectType<UpdateWriteOpResult>(user);
```suggestion
  const replaceOneResult = await User.replaceOne({}, {});
  expectType<UpdateWriteOpResult>(replaceOneResult);
```

2022-08-30 14:17 UTC, hasezoey approved these changes
LGTM
The mentioned issue this PR resolves should maybe be added under "development" (or through original message `fixes` or `closes`)

2022-08-30 15:29 UTC, merged