Add clarification about overwrite flag in model.js
Automattic/mongoose pull request #12447
Opened 2022-09-20 11:45 UTC by Tzvika-m

Add calrification for using the `overwrite` flag in model.findByIdAndUpdate and model.findOneAndUpdate

**Summary**

The way mongoose changes the update behaviour (adds `$set` to the update command) and how to prevent it is not intirely clear.
I believe this note could help save some time and effort for future users.

2022-09-20 15:05 UTC, Uzlopak requested changes
For me this change has no additional value as it just says see overwrite. It should have more than "see overwrite".

2022-09-21 07:25 UTC, Tzvika-m commented
@Uzlopak What did you have in mind?

2022-09-22 08:17 UTC, hasezoey approved these changes
LGTM, i think it helps having a note to the option to prevent the automatic extra behavior form happening (if the option exists) in the example itself

some small things to suggest to keep the naming more consistent

2022-09-22 08:17 UTC, hasezoey commented on lib/model.js
> + * To prevent this behaviour, see the `overwrite` flag
```suggestion
 * To prevent this behaviour, see the `overwrite` option
```

2022-09-22 08:17 UTC, hasezoey commented on lib/model.js
> + * To prevent this behaviour, see the `overwrite` flag
```suggestion
 * To prevent this behaviour, see the `overwrite` option
```

2022-09-22 08:28 UTC, Uzlopak approved these changes
I guess I follow in this case @hasezoey

2022-09-22 10:30 UTC, Tzvika-m commented
Great, thanks
I've committed your suggestions @hasezoey

2022-09-22 11:24 UTC, merged