Gh 9541 create mergeDiscriminatorSchema function
Automattic/mongoose pull request #12452
Opened 2022-09-20 21:58 UTC by IslandRhythms

2022-09-22 08:30 UTC, hasezoey commented on lib/helpers/discriminator/mergeDiscriminatorSchema.js
> +      to[key] = from[key];
i think this alert can be dismissed thanks to the check of [`specialProperties.has(key)`](https://github.com/Automattic/mongoose/pull/12452/files#diff-c1a625c1ae3ad53e2e66df88c3bb0ff96db3dd8e4cdca58d2ec8ca40275ada26R41-R43)

2022-09-22 08:30 UTC, hasezoey commented on lib/helpers/discriminator/mergeDiscriminatorSchema.js
> +      to[key] = from[key];
i think this alert can be dismissed thanks to the check of [`specialProperties.has(key)`](https://github.com/Automattic/mongoose/pull/12452/files#diff-c1a625c1ae3ad53e2e66df88c3bb0ff96db3dd8e4cdca58d2ec8ca40275ada26R41-R43)

2022-09-22 08:32 UTC, Uzlopak commented on lib/helpers/discriminator/mergeDiscriminatorSchema.js
> +      to[key] = from[key];
I agree

2022-09-22 08:33 UTC, Uzlopak commented on lib/helpers/discriminator/mergeDiscriminatorSchema.js
> +      to[key] = from[key];
Dismissed

2022-09-22 08:33 UTC, Uzlopak commented on lib/helpers/discriminator/mergeDiscriminatorSchema.js
> +      to[key] = from[key];
Dismissed

2022-09-22 08:33 UTC, hasezoey commented
should the option `isDiscriminatorSchemaMerge` now be removed from `utils.merge` in this PR too, or is it still used in other places?

2022-09-26 15:24 UTC, vkarpov15 requested changes
Couple of suggestions to refactor. Ideally I'd like to call `mergeDiscriminatorSchema()` without any options.

2022-09-26 15:24 UTC, vkarpov15 commented on lib/helpers/discriminator/mergeDiscriminatorSchema.js
> +    if (omitNested[path]) {
Get rid of `omitNested` and replace this check with `if (path === 'tree' && from != null && from.instanceOfSchema)`

2022-09-26 15:24 UTC, vkarpov15 commented on lib/helpers/discriminator/mergeDiscriminatorSchema.js
> +    if (options.omit && options.omit[key]) {
Remove the `omit` option and just check if `key` is either 'discriminators', 'base', or '_applyDiscriminators' here.

2022-09-30 00:57 UTC, vkarpov15 approved these changes

2022-09-30 00:59 UTC, merged