feat(schema): add `alias()` method that makes it easier to define multiple aliases for a given path
Automattic/mongoose pull request #12491
Opened 2022-09-30 15:42 UTC by vkarpov15

Fix #12368

**Summary**

One approach we recommend for renaming fields from API requests is using aliases. Here's an example of [using an alias to convert the GitHub API's `avatar_url` response to `avatar` in Mongoose](https://github.com/mongoosejs/backend/blob/7a40a525291dc2e284b78829b453b1ac59926385/src/db/subscriber.js#L8). But right now there's no way to define multiple aliases for a single field. This PR adds a new schema method, so you can do something like `schema.alias('avatar', ['avatar_url', 'photo'])`.

**Examples**

2022-09-30 16:10 UTC, hasezoey requested changes
LGTM, with some minor details

changes to the types still need to be done

2022-10-03 08:35 UTC, AbdelrahmanHafez requested changes
Nice!

Would also be great if we make the API support arrays of strings as follows:
```js
const schema = new Schema({
  avatar: { type: String, alias: ['avatarURL', 'avatarImageURL'] }
});
```

Also, would be nice if we could have TS types and tests for those changes.

2022-10-04 06:59 UTC, hasezoey commented on lib/schema.js
> +    }
with the updates, couldnt this be changed to just `aliasFields(this, { [path]: alias })`? (or combine array and non-array paths)?

2022-10-04 07:01 UTC, hasezoey commented
also just to be sure, where is checked that a `alias` cannot be a special name like `__proto__`/`prototype`?

2022-10-05 06:40 UTC, AbdelrahmanHafez approved these changes
LGTM, thanks 👍

2022-10-05 16:44 UTC, hasezoey approved these changes
LGTM

2022-10-05 21:05 UTC, merged