fix(schema): `Schema.add` should add properties to schema's `.obj`
Automattic/mongoose pull request #12823
Opened 2022-12-22 08:21 UTC by lpizzinidev

fix #12799 

**Summary**
Adding a property with the `Schema.add` method was not adding it to the `.obj` object of the schema.

**Examples**
```
const schema = new Schema();
schema.add({ test: String });
console.log(schema.obj); // Was undefined, now contains the `test` property
```

2022-12-26 22:54 UTC, vkarpov15 requested changes
A couple of problems with the PR. I'd also like to hear why OP is using `obj`. Because `obj`  is documented as "The original object passed to the schema constructor", so according to the docs the current behavior is correct:

![image](https://user-images.githubusercontent.com/1620265/209587338-0ae94360-5b5d-47a0-9415-00eb6719dd3e.png)

2022-12-26 22:54 UTC, vkarpov15 commented on lib/schema.js
> +      key !== '_id' &&
Why ignore `_id` and `__v`? `schema.add({ _id: Number })` should be valid.

2022-12-26 22:54 UTC, vkarpov15 commented on lib/schema.js
> +      !(key in this.obj)
`.add()` overwrites keys, so I don't think this check is necessary

2022-12-27 09:45 UTC, lpizzinidev commented
@vkarpov15 
I missed the documentation about `obj`.
If that is the definition then the issue is not a bug (just expected behavior) and should be closed, as well as this PR.
If you think that the new behavior is an improvement I will update the docs and apply the suggested changes.

2022-12-29 17:40 UTC, vkarpov15 commented
In that case, I'll close this PR for now. We may re-open it in the future if it turns out we have reason to improve `.obj`.

2022-12-29 17:40 UTC, closed without merging