list all possible strings for schema.pre
Automattic/mongoose pull request #12868
Opened 2023-01-03 21:55 UTC by IslandRhythms

2023-01-06 16:54 UTC, vkarpov15 requested changes

2023-01-06 16:54 UTC, vkarpov15 commented on docs/middleware.md
> +Here are the possible strings that can be passed to `pre()`
You're missing a whole bunch. `estimatedDocumentCount`, `findOneAndReplace`, `aggregate`, `insertMany`, and more.

Also, please put this list immediately after "* [insertMany](api/model.html#model_Model-insertMany)" on L69

2023-01-08 01:44 UTC, jdevries3133 commented
Hey folks, is it possible to extend an opportunity to @larasodjati to draft a PR for the issue she's identified here?

Lara is a student in an org I'm volunteering for and I'm hoping to sponsor / assist her to see this issue through to a merged PR.

Obviously totally understand if you want to close this out quickly, and @IslandRhythms, your work is definitely appreciated and I wouldn't want to step on your toes either. In any case, it would be great if we could open an opportunity for Lara to make her first open source contribution!

Thanks all!

2023-01-09 15:52 UTC, IslandRhythms commented
I have no objection but I'll need to confirm with val if its ok.

2023-01-09 16:17 UTC, IslandRhythms commented
Val would rather me do it, sorry.

2023-01-09 16:46 UTC, vkarpov15 approved these changes
Thanks :+1:

2023-01-09 16:47 UTC, vkarpov15 commented
@jdevries3133 sorry we missed your post, this PR is already done. But I appreciate the offer. Please let me know if you want another light docs issue that your student can help out with.

2023-01-09 16:47 UTC, vkarpov15 approved these changes
Thanks :+1:

2023-01-09 16:47 UTC, merged

2023-01-09 16:49 UTC, jdevries3133 commented
> @jdevries3133 sorry we missed your post, this PR is already done. But I appreciate the offer. Please let me know if you want another light docs issue that your student can help out with.

No worries, totally understand. We'll definitely be on the lookout for another light docs issue, if you have a suggestion that would be much appreciated!