Fix/context cast undefined
Automattic/mongoose pull request #12909
Opened 2023-01-14 23:09 UTC by MohOraby

fix #12902 caused by `context` being undefined causing TypeError.

2023-01-14 23:22 UTC, AbdelrahmanHafez commented
Welcome @MohOraby 👋 
Can you please also add the original test from the issue to verify that the whole flow works?

2023-01-14 23:23 UTC, AbdelrahmanHafez requested changes
Welcome @MohOraby 👋
Can you please also add the original test from the issue to verify that the whole flow works?

2023-01-15 00:28 UTC, AbdelrahmanHafez commented on test/model.test.js
> +  it('returns document with nested schema', async function() {
```suggestion
  it('returns document with nested schema (gh-12902)', async function() {
```

2023-01-15 01:12 UTC, AbdelrahmanHafez commented on test/cast.test.js
> +    const nested = new Schema({ _id: Number }, {});
```suggestion
  it('returns cast value with context undefined for nested schema (gh-12902)', function() {
    const nested = new Schema({ _id: Number });
```

2023-01-15 11:21 UTC, MohOraby commented
Hello @vkarpov15 👋🏻
When trying to run the tests, deno tests fail with unexpected results
unless specifying `{ strictQuery: true }` the casted query is returning properties that aren't part of the schema
I think `strictQuery` is defaulting to false in that case

2023-01-23 22:32 UTC, vkarpov15 commented
Closing this one in favor of #12915.

2023-01-23 22:32 UTC, closed without merging