test: some cleanup re: #12890
Automattic/mongoose pull request #12919
Opened 2023-01-17 16:00 UTC by vkarpov15

**Summary**

Applied some suggestions from #12890. Mostly getting rid of unnecessary `connectionsToClose` - left it in one case where it makes sense. Also refactored out some `Model.watch()` cases, and fixed a potential bug due to the MongoDB node driver continuing to poll after change stream is closed.

**Examples**

2023-01-17 16:22 UTC, hasezoey requested changes
mostly looks good to me, though there are some places that have not been changed yet, or were changed back to not properly close in case of test failure

2023-01-17 16:22 UTC, hasezoey commented on test/collection.capped.test.js
>      const db = start();
```suggestion
    db = start();
```

2023-01-17 16:22 UTC, hasezoey commented on test/collection.test.js
> +  this.afterEach(async function() {
```suggestion
  afterEach(async function() {
```

i dont think `this.` is required here, removing it to make it consistent with other test files

2023-01-17 16:22 UTC, hasezoey commented on test/model.test.js
>      const db = start({ noErrorListener: true });
from what i can tell, in this file / tests the connections do not get properly closed if the test is not successful (which `connectionsToClose` would solve)

2023-01-23 22:23 UTC, IslandRhythms approved these changes
LGTM

2023-01-23 22:36 UTC, merged