types(model): fix type of options of Model.aggregate
Automattic/mongoose pull request #12933
Opened 2023-01-23 14:08 UTC by ghost91-

**Summary**

This change adjusts the type of the `options` parameter of `Model.aggregate` to be the `AggregateOptions` type from mongoose, instead of the one from mongodb. The aggregate method just passes this parameter on to `Aggregate.option`, which is already typed to accept the `AggregateOptions` type from mongoose, so this seems like the correct choice.

The 2 types mostly seem to be compatible anyways, but there is a small inconsistency that makes them incompatible: `mongodb.AggregateOptions` specifies that the `session` property may be a `ClientSession`, or `undefined` (but not `null`), while the `AggregateOptions` type from mongoose also allows `null`. So maybe that also should simply be aligned.

2023-01-23 18:58 UTC, vkarpov15 requested changes
This should work fine, but to reduce the risk of any backwards breaking changes, can we change `AggregateOptions` to something like the following?

```ts
interface AggregateOptions extends Omit<mongodb.AggregateOptions, 'session'>, SessionOption {
    [key: string]: any;
  }
```

That seems to work fine, and makes it so that there's no chance we missed an option from `mongodb.AggregateOptions`.

2023-01-24 09:25 UTC, ghost91- commented
I have incorporated the suggestion. Before doing so, I have manually verified that there are no differences between the 2 `AggregateOptions` types, aside from allowing `null` as the `session` property.

2023-02-04 17:52 UTC, vkarpov15 approved these changes
Thanks :+1:

2023-02-04 17:52 UTC, vkarpov15 approved these changes
Thanks :+1:

2023-02-04 17:54 UTC, merged