BREAKING CHANGE: make exported model just an interface, rename exported Model const -> ModelClass
Automattic/mongoose pull request #12935
Opened 2023-01-23 18:45 UTC by vkarpov15

Fix #12873

**Summary**

#12873 points out that we have some odd legacy behavior with `Model`: `Model` is both an interface and a `const`. Besides being a bit confusing, this is a bit dangerous because it allows people to do `import { Model } from 'mongoose'; Model.findOne();`, which is ideally something that Mongoose should block. Seems like a "why would anyone do that?", but we have a couple of test cases (the ones this PR removes) that accidentally pass because they make use of that exact pattern :) 

Only downside is that classes that `extends Model` are no longer supported. Which didn't work well anyway, because `extends Model` implies `Model<any>`, and also creates a `Model` class that isn't connected to any connection, which would fail at runtime.

@hasezoey what do you think?

**Examples**

2023-01-23 19:08 UTC, hasezoey requested changes
The change looks good, though with some questions to resolve

2023-01-23 19:08 UTC, hasezoey commented on test/types/queries.test.ts
> -async function gh11602(): Promise<void> {
maybe consider instead of removing just changing it to a actual model

2023-01-23 19:08 UTC, hasezoey commented on types/models.d.ts
> +  export interface Model<T, TQueryHelpers = {}, TMethodsAndOverrides = {}, TVirtuals = {}, TSchema = any> extends
maybe consider adding tsdoc explaining what the difference between `ModelClass` and `Model` is

2023-01-23 19:08 UTC, hasezoey commented on test/types/generics.test.ts
> -import { Model, Document } from 'mongoose';
maybe consider instead of removing just changing it to a actual model

2023-02-04 17:51 UTC, merged

2023-02-22 11:50 UTC, hasezoey commented
Would be good if this change would also be documented in the migration guide

2023-02-22 11:52 UTC, hasezoey commented
just noticed that this change does not allow `model instanceof mongoose.Model` anymore (which works at runtime), because no type named `Model` exists (only a interface) and `ModelClass` does not exist at runtime from what i know

2023-02-22 15:39 UTC, vkarpov15 commented
@hasezoey that's a good point. Do you think it is worthwhile to revert this change? I made this change assuming that there wouldn't be any significant impact on end users, but `model instanceof mongoose.Model` not working in TypeScript anymore sounds significant.

2023-02-22 16:36 UTC, hasezoey commented
> Do you think it is worthwhile to revert this change?

you can do 1 of 2 options:
- revert the change to how it was before, in just types
- add at runtime a alias for `Model` as `ModelClass`