Allow this typing in validator functions
Automattic/mongoose pull request #12938
Opened 2023-01-24 01:39 UTC by Freezystem

**Summary**

Improve ability to type validator functions by allowing to define the `this` keyword. This avoid type errors when using `this` in the function body.

**Examples**

```ts
export const refExists: ValidateOpts<Types.ObjectId> = {
	async validator(_id: Types.ObjectId, props: ValidatorProps & Record<string, unknown>): Promise<boolean> {
		const self = this.constructor as Model<unknown>;
		const {ref} = self.schema.paths[props.path].options;
		const model = models[ref as string];

		return await model.exists({_id}).exec() !== null;
	},
	message: 'REF_ID_DOES_NOT_EXISTS',
	propsParameter: true,
};
```
return the following error on this.constructor;

> any
> Unsafe member access .constructor on an `any` value. `this` is typed as `any`.
> You can try to fix this by turning on the `noImplicitThis` compiler option, or adding a `this` parameter to the function.eslint[@typescript-eslint/no-unsafe-member-access](https://typescript-eslint.io/rules/no-unsafe-member-access)

2023-02-04 17:38 UTC, vkarpov15 requested changes

2023-02-04 17:38 UTC, vkarpov15 commented on types/validation.d.ts
> +    (this: M, value: T, props?: ValidatorProps<T> & Record<string, any>): boolean;
`this` should be a HydratedDocument, not `Model`. Remember `Model` is a type, so `this` would be a model class, not an instance of a model class. I'd change the generic def from `M = Model<unknown>` to `THydratedDocumentType = HydratedDocument<unknown>`

2023-02-04 17:38 UTC, vkarpov15 commented on types/validation.d.ts
>    type SchemaValidator<T> = RegExp | [RegExp, string] | Function | [Function, string] | ValidateOpts<T> | ValidateOpts<T>[];
Without changing `SchemaValidator`, and `SchemaTypeOptions`, there's no way for user to set `M`?

2023-04-05 21:26 UTC, vkarpov15 commented
@Freezystem do you want to continue work on this PR?

2023-04-06 11:01 UTC, Freezystem commented
Hey, sorry I'm actually very busy and I will not have the time to work on it for the moment.  
We can close this one until someone else fixes it or I get time to do it myself.

2023-04-06 17:44 UTC, closed without merging