type(query): changed return type of lean() to include null
Automattic/mongoose pull request #13155
Opened 2023-03-10 07:53 UTC by lpizzinidev

**Summary**
The `lean()` method return type has been changed to `QueryWithHelpers<LeanResultType | null, DocType, THelpers, RawDocType>`.

Closes #13151

2023-03-11 17:25 UTC, vkarpov15 requested changes

2023-03-11 17:25 UTC, vkarpov15 commented on test/types/lean.test.ts
> +    if (!doc2) return;
This change is unfortunately a blocker. You should never need `if (!doc2)` if you have `orFail()`.

2023-03-11 17:25 UTC, vkarpov15 commented on test/types/lean.test.ts
> +  if (!docs) return;
This one is also unfortunately a red flag. `find()` can never return `null`, so something is incorrect here.

2023-03-11 17:25 UTC, vkarpov15 commented on types/query.d.ts
> +    lean<LeanResultType = ResultType extends any[] ? Require_id<RawDocType>[] : Require_id<RawDocType>>(val?: boolean | any): QueryWithHelpers<LeanResultType | null, DocType, THelpers, RawDocType>;
Probably need an extra condition here to only add `null` if `ResultType` is nullable. That should work around the `orFail()` issue.

2023-03-13 11:57 UTC, hasezoey commented on types/query.d.ts
> +    lean<LeanResultType = ResultType extends any[] ? Require_id<RawDocType>[] : Require_id<RawDocType>>(val?: boolean | any): QueryWithHelpers<null extends ResultType ? LeanResultType | null : LeanRe
any reason this is written as `null extends Type` instead of `Type extends null` like other parts of the code?

2023-03-22 20:06 UTC, vkarpov15 approved these changes
Thanks :+1:

2023-03-22 20:06 UTC, merged