feat(schema): consistently add `.get()` function to all SchemaType classes
Automattic/mongoose pull request #13438
Opened 2023-05-25 15:17 UTC by vkarpov15

Re: #7156

**Summary**

Looks like some schematypes are missing the `get()` function to register a getter for all instances of the schematype. Only numbers, strings, and ObjectIds currently have that function. This came up in #7156 in the context of dates.

Not urgent because there is an easy workaround, but something we should ship for 7.3.

**Examples**

2023-05-25 16:57 UTC, AbdelrahmanHafez reviewed
Maybe add a test
```js
[...schemaTypes].forEach(schemaType=> {
  it(`${schemaType.name} has a \`get\` method`, ()=> {
    assert.strictEqual(typeof schemaType.get, 'function');
  });
})
```

2023-05-25 18:28 UTC, hasezoey requested changes
looks good, though some examples need adjustment

2023-05-25 18:28 UTC, hasezoey commented on lib/schema/date.js
> + * Attaches a getter for all ObjectId instances
```suggestion
 * Attaches a getter for all Date instances
```

2023-05-25 18:28 UTC, hasezoey commented on lib/schema/date.js
> + *     // Always convert to string when getting an ObjectId
```suggestion
 *     // Always convert Dates to string
```

2023-05-25 18:28 UTC, hasezoey commented on lib/schema/bigint.js
> + *     mongoose.Schema.BigInt.get(v => v == null ? number : Number(v));
```suggestion
 *     mongoose.Schema.BigInt.get(v => v == null ? v : Number(v));
```

2023-05-26 15:00 UTC, hasezoey approved these changes

2023-05-26 15:21 UTC, merged