Island rhythms/gh 13510
Automattic/mongoose pull request #13538
Opened 2023-06-22 21:37 UTC by IslandRhythms

2023-06-23 16:17 UTC, IslandRhythms commented
The test passes on my machine so I'm not sure why its failing here

2023-06-26 20:59 UTC, vkarpov15 requested changes

2023-06-26 20:59 UTC, vkarpov15 commented on test/schematype.test.js
> +        await m.connect('mongodb://127.0.0.1:27017/gh13510');
Why did you hard code the connection string here? There's nowhere else in the tests, other than a very old sharding test, where we hard code the connection string. Use `mongoose.connect(start.uri)` instead.

2023-06-27 13:38 UTC, vkarpov15 commented
Link #13510 to this issue

2023-06-28 18:26 UTC, merged