feat: allow top level dollar keys with findOneAndUpdate(), update()
Automattic/mongoose pull request #13786
Opened 2023-08-26 21:40 UTC by vkarpov15

**Summary**

Right now, MongoDB allows storing top-level keys that start with $, but our `castUpdate()` function doesn't allow top-level dollar keys.

```javascript
'use strict';
  
const mongoose = require('mongoose');
mongoose.set('debug', true);

void async function main() {
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
  //await mongoose.connection.dropDatabase();

  await mongoose.connection.collection('test').insertOne({ $set: [1,2, 3, 4] });
  console.log(await mongoose.connection.collection('test').find().toArray());
  console.log('Done');
}();
```

**Examples**

2023-08-27 08:31 UTC, hasezoey submitted a review, later dismissed

2023-08-27 08:32 UTC, hasezoey commented
since when does mongodb allow that? because mongodb 4.4 tests fail with "not allowed"

2023-08-28 18:18 UTC, AbdelrahmanHafez requested changes
I second hasezoey's concern, I feel like we should either:
A) err on the side of caution for now and keep blocking adding keys that start with `$`.
B) Make it conditional, by fetching the server information and making sure it supports those keys.

A more performant alternative approach to B is to keep things as is in the PR, but add error-handling that throws an error an error along these lines: `mongo does not allow storing keys that start with a $ sign, please upgrade your mongodb server version to version x.y or later`.

2023-08-28 19:53 UTC, vkarpov15 commented
It looks like MongoDB 5 was the first version to support top-level keys that start with $.

I disagree that we should be checking the MongoDB server version for 2 reasons:

1. Historically, Mongoose has never relied on MongoDB server version. As new features are introduced, we support them, and rely on the MongoDB server to throw an error if you use a feature that a particular version of the MongoDB server doesn't support. For example, we didn't implement server version checks for change streams, transactions, etc.
2. It is entirely possible to have multiple versions of MongoDB in one replica set, or even have one version of a mongos proxy in front of a different version of mongod replica set. So "what is the current MongoDB version?" is a more nuanced version than one might think when you're talking about a library that connects to MongoDB and enables/disables functionality based on version. And opens the door to us having to test what happens during MongoDB server version upgrades.

2023-08-28 21:54 UTC, AbdelrahmanHafez commented
Fair points, we can just leave it up to the server to throw the proper errors when needed while supporting the feature for those who have more recent versions.

2023-08-28 21:55 UTC, AbdelrahmanHafez approved these changes

2023-08-29 08:34 UTC, hasezoey approved these changes
looks good to me, but this should definitely be mentioned in the changelog and in the documentation that only mongodb 5 and up support top-level `$` keys

2023-08-29 16:25 UTC, merged