fix: Remove count() from TypeScript definitions
Automattic/mongoose pull request #14076
Opened 2023-11-11 18:23 UTC by ffflorian

**Summary**

After https://github.com/Automattic/mongoose/pull/13618 was merged, the now missing `count()` function was not removed from the types.

**Examples**

2023-11-12 20:27 UTC, AbdelrahmanHafez approved these changes

2023-11-12 20:31 UTC, AbdelrahmanHafez requested changes
Can you please rebase your branch on `8.0` since #13618 seems to be merged into `8.0` branch.

2023-11-14 02:24 UTC, vkarpov15 approved these changes
Thanks :+1:

2023-11-14 02:25 UTC, vkarpov15 commented
Going to merge this into a separate branch so I can fix up the test failures

2023-11-14 02:25 UTC, merged

2023-11-14 21:56 UTC, ffflorian commented
Thanks for taking over @vkarpov15 and @AbdelrahmanHafez!