fix: cast error when there is an elemMatch in the and clause
Automattic/mongoose pull request #14171
Opened 2023-12-11 03:54 UTC by tosaka-n

**Summary**
- after this PR is merged
	- https://github.com/Automattic/mongoose/pull/13938
- Error in cast because options.discriminatorKey is obtained before checking if the schema is null
	- here:
		- https://github.com/Automattic/mongoose/pull/13938/files#diff-5078cdf8af89c694947cdcb5e60fcd3e29dda608e62642ecf5fc3eeb97e43ce1R71
- Changed to refer to context.schema as well as this PR
	- https://github.com/Automattic/mongoose/commit/266804b995ae715cd4746d0e5b687e7fb96441fc

**Examples**
query:
```
{
  users: {
    $elemMatch: {
      $and: [
        { name: "test" },
        $or: [
          { is_deleted: true },
          { is_deleted: null } 
        ]
      ]
    }
  }
}
```

2023-12-11 04:12 UTC, satoshun00 commented on lib/schema/array.js
> +function createLogicalQueryOperatorHandler(op, context) {
It doesn't seem necessary to take `context` as an argument in this scope.

2023-12-13 20:21 UTC, vkarpov15 requested changes
Code is LGTM, but can you please add a test case?

2023-12-14 09:58 UTC, tosaka-n commented on test/model.query.casting.test.js
> +  it('should not throw a cast error when dealing with an array of objects in combination with $elemMatch and nested $and', async function() {
nits: I couldn't think of an appropriate test name, so I'm open to suggestions.

2023-12-21 16:18 UTC, vkarpov15 approved these changes
Thanks :+1:

2023-12-21 16:18 UTC, merged