feat: add transactionAsyncLocalStorage option to opt in to automatically setting session on all transactions
Automattic/mongoose pull request #14742
Opened 2024-07-11 16:17 UTC by vkarpov15

Backport #14583 to 7.x
Re: #13889

**Summary**

Add `transactionAsyncLocalStorage` option to 7.x. Should work fine because Node v14.x has "experimental" support for the same AsyncLocalStorage API that became stable in 16.x.

**Examples**

2024-07-11 18:44 UTC, hasezoey requested changes
Code looks good to me, though i would recommend to add a note to the documentation that it makes use of a experimental nodejs API below `16.4.0` (as added in the types by me and listed [under `AsyncLocalStorage`'s History](https://nodejs.org/api/async_context.html#class-asynclocalstorage)).

also i just noticed that option `transactionAsyncLocalStorage` (in latest docs) only returns a result for `docs/transactions.html`, maybe it should be mentioned as a possible option for `mongoose.set`.

aside from that, there are some minor doc suggestions that should be done.

2024-07-11 18:44 UTC, hasezoey commented on docs/transactions.md
> +Mongoose 8.4 is able to set the `session` operation on all operations within a `Connection.prototype.transaction()` executor function using Node's [AsyncLocalStorage API](https://nodejs.org/api/async
```suggestion
Mongoose 7.8 is able to set the `session` operation on all operations within a `Connection.prototype.transaction()` executor function using Node's [AsyncLocalStorage API](https://nodejs.org/api/async_context.html#class-asynclocalstorage).
```

2024-07-11 18:44 UTC, hasezoey commented on types/mongooseoptions.d.ts
> +     * Set to true to make Mongoose use Node.js' built-in AsyncLocalStorage (Node >= 16.0.0)
```suggestion
     * Set to true to make Mongoose use Node.js' built-in AsyncLocalStorage (Added in: v13.10.0, v12.17.0; Stable since 16.4.0)
```

2024-07-13 13:39 UTC, hasezoey reviewed
LGTM, would wait until #14744 is merged (and included here) before approving

2024-07-15 13:39 UTC, vkarpov15 commented
@hasezoey I backported #14744 in e909e0b, can you take a look?

2024-07-15 13:40 UTC, hasezoey approved these changes

2024-07-19 17:01 UTC, merged