feat(model+query): support `options` parameter for distinct()
Automattic/mongoose pull request #14772
Opened 2024-08-01 15:07 UTC by vkarpov15

Fix #8006

**Summary**

Make it easier to use `distinct()` with transactions, so you don't need to chain `setOptions()`. `distinct()` looks to be the only query function where you can't pass in `options`.

**Examples**

2024-08-02 10:51 UTC, hasezoey requested changes
LGTM, but the `options` parameter still needs to be added to the query types (currently only in the model's types) and a similar test to `using options parameter for distinct` on query should likely be in for Model too, or is the transaction test enough?

As a note, the `Model.distinct` and `Query.prototype.distinct` have differing `options` checks, is this intentional?

2024-08-02 10:51 UTC, hasezoey commented on test/docs/transactions.test.js
> +    const session = await db.startSession();
```suggestion
    const Character = db.model('gh8006_Character', new Schema({ name: String, rank: String }, { versionKey: false }));

    const session = await db.startSession();
```

i dont know if this intended, but i think a single new line would be enough

2024-08-08 00:07 UTC, vkarpov15 commented
Thanks for the suggestions @hasezoey , I've implemented them both. Added `options` param to query `distinct()` types and removed the `typeof options === 'object'` check in Query.prototype.distinct (and countDocuments() + estimatedDocumentCount() for consistency)

2024-08-08 13:03 UTC, hasezoey approved these changes

2024-08-08 18:35 UTC, merged