changes not being reflected
Automattic/mongoose pull request #9891
Opened 2021-02-02 18:02 UTC by IslandRhythms

These changes worked in my local environment but for some reason when I run it, the code ignores everything

2021-02-02 18:08 UTC, vkarpov15 commented on test/document.test.js
> +    mongoose.connect('mongodb://localhost/test', {useNewUrlParser: true, useUnifiedTopology: true});
I'd just get rid of lines 9935-9937, not necessary

2021-02-02 19:17 UTC, IslandRhythms commented
The failure's are not caused by my test. They are caused by gh9884

2021-02-02 19:23 UTC, IslandRhythms commented
I checked gh9884 on my machine and it passed no problem

2021-02-02 19:49 UTC, IslandRhythms commented
I believe the two failures are unrelated to my changes so should be good to go.

2021-02-02 20:48 UTC, vkarpov15 requested changes

2021-02-02 20:48 UTC, vkarpov15 commented on test/document.test.js
> +        done();
`done()` should be on line 9982 instead of `failing;`, the test isn't done until the `new Test({ prop: 'Test 3' })` code is done running

2021-02-03 15:55 UTC, vkarpov15 approved these changes
Nice :+1:

2021-02-03 15:55 UTC, merged